version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7

    working_directory: ~/stevens_shuttles

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Pipfile.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: set pythonpath
          command: export PYTHONPATH=$PYTHONPATH:~/stevens_shuttles/lib

      - run:
          name: install dependencies
          command: |
            python3 -m pip install pipenv
            pipenv install

      - save_cache:
          paths:
            - ~/.virtualenvs
          key: v1-dependencies-{{ checksum "Pipfile.lock" }}

      - run:
          name: run tests
          command: |
            mkdir test-reports
            pipenv run $PYTHONPATH
            pipenv run pytest --junitxml=test-reports/junit.xml

      - store_test_results:
          path: test-reports

      - store_artifacts:
          path: test-reports
